package Silex::Web::Donnenwa::Model::DonDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Silex::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:dondb:localhost',
        user => 'don',
        password => 'gksdud09',
        mysql_enable_utf8 => 1,
    }
);

=head1 NAME

Silex::Web::Donnenwa::Model::DonDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Silex::Web::Donnenwa>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Silex::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.59

=head1 AUTHOR

meadow

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
