CREATE TABLE charge (
    id          INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    applicant   VARCHAR(32) NOT NULL DEFAULT '',
    title       VARCHAR(128) NOT NULL DEFAULT '',
    content     TEXT NOT NULL DEFAULT '',
    money       INT UNSIGNED NOT NULL DEFAULT '0',
    created_on  DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
    updated_on  DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE picture (
    id    INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    idx   INT NOT NULL DEFAULT '',
    path  TEXT NOT NULL DEFAULT '',
    name  TEXT NOT NULL DEFAULT '',
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
